### ISSUE TITLE
Add num_gpus config parameter

### ISSUE THREAD

**Issue by wsnoble** [Noble-Lab/casanovo#173]
I think we should add a parameter to the config file that species the number of GPUs Casanovo uses, rather than relying on an environment variable.  If the parameter is set to 0, then Casanovo would use the CPU only.  It may be sensible to also check the environment variable and issue a warning (or error?) if the user requests more GPUs than the environment variable says are available.

**Comment by bittremieux** [comment]
If there are multiple GPUs how should Casanovo choose the ones to use? I.e. you have 4 GPUs and set `num_gpus=2`, which ones do you use? Imo the `CUDA_VISIBLE_DEVICES` is a standard approach across any GPU application and is well understood (caveat: by people who develop on the GPU, but we clearly mention it in the documentation), so I see limited use in reimplementing the same/similar functionality on our end.

**Comment by bittremieux** [comment]
I actually think our current functionality fits with how most people will use Casanovo: by running it on a dedicated (rather than a shared) system. In that case, maximally using CPU and GPU transparently makes sense.

I don't really see a benefit in reinventing the wheel. Currently we can just ignore complexity that would arise by having to choose specific GPUs and have [super simple code to select GPUs](https://github.com/Noble-Lab/casanovo/blob/main/casanovo/denovo/model_runner.py#L161). And we don't lose out on specific functionality, because users can easily set `CUDA_VISIBLE_DEVICES` if necessary.

I do agree that our documentation about this can and should be improved.

**Comment by wfondrie** [comment]
I think I struck a good compromise in my PR. I've added two new parameters and removed `no_gpu`:
```yaml
# The hardware accelerator to use. Must be one of:
# “cpu”, “gpu”, “tpu”, “ipu”, “hpu”, “mps”, or “auto”
accelerator: "auto"
# The devices to use. Can be set to a positive number int,
# or the value -1 to indicate all available devices should be used,
# If left empty, the appropriate number will be automatically
# selected for automatic selected on the chosen accelerator.
devices:
```

The defaults for both should be good for a vast majority of folks.
